version: '3.5'

services:
  reportserver:
    image: dulce/report-server:dev
    build:
      context: ../../
      dockerfile: Docker/Dev/Server/Dockerfile

  reportclient:
    image: dulce/report-client:dev
    build:
      context: ../../
      dockerfile: Docker/Dev/Client/Dockerfile
